sudo: false

language:
  - python

python:
  - 3.8

install:
  - pip install -r requirements.txt

script:
  - pycodestyle instapy
  - pytest --verbose --capture=no instapy
  - pip install .

notifications:
  email: quarterwire@outlook.com
